name: "Sync & Deploy Workflow"
description: "Synchronize content with Google Drive and prepare for deployment"

trigger:
  type: "automatic"
  conditions:
    - "content-generation completed"
    - "competitive-analysis completed"

steps:
  1:
    agent: "typescript-pro"
    task: "Build & Test Preparation"
    actions:
      - "Run TypeScript compilation"
      - "Execute linting and formatting"
      - "Validate configuration files"
      - "Check markdown structure"
    outputs:
      - "build-report.md"

  2:
    agent: "javascript-pro"
    task: "Google Drive Synchronization"
    depends_on: [1]
    actions:
      - "Execute sync process with Google Drive"
      - "Validate file transfers"
      - "Handle sync conflicts"
      - "Generate sync reports"
    outputs:
      - "sync-report.md"
      - "Updated Google Drive documents"

  3:
    agent: "documentation-engineer"
    task: "Content Organization"
    depends_on: [2]
    actions:
      - "Organize files in proper structure"
      - "Update index and navigation"
      - "Generate content catalogs"
      - "Create cross-references"
    outputs:
      - "content-index.md"
      - "Updated file structure"

  4:
    agent: "qa-expert"
    task: "Deployment Validation"
    depends_on: [1, 2, 3]
    actions:
      - "Validate all files are properly synced"
      - "Check content accessibility"
      - "Verify metadata integrity"
      - "Test markdown rendering"
    outputs:
      - "deployment-validation-report.md"

completion:
  conditions:
    - "All content synchronized successfully"
    - "Validation tests passed"
    - "Content ready for consumption"